### ISSUE TITLE
maximum similarity to "a part of" the existing usernames

### ISSUE THREAD

**Issue by AliCihan** [oplik0/nodebb-plugin-restrict-usernames#22]
Hi @oplik0 , 

Instead of including all usernames, can we have an option to specify a list of usernames or group names? 

We want to limit the usernames to the moderators and highly active users who are in specific groups(these users are added to these groups automatically by their post or reputation numbers)...

With the user base growing steadily, a very general approach is causing some issues. Could the plugin prompt us to input the usernames or group names to be checked for this rule? We can provide a list of usernames or, preferably, specify a group name for these members. This would be more efficient, especially since new active members are periodically added to these groups.

Thank you very much in advance.

**Comment by oplik0** [comment]
Sure, I'll look into that in a few days (remind me if I don't add it or at least respond in like a week)

**Comment by oplik0** [comment]
Added in 0.7.0 - the groups selection applies to similarity and the new phonetic filters, the rest work same way they did before.
