### ISSUE TITLE
Case-insensitive Rules?

### ISSUE THREAD

**Issue by nfeddema** [oplik0/nodebb-plugin-restrict-usernames#6]
It would be great it there were a way to do case-insensitive rules.  Maybe the `duplicate` user filter could flip the 'i' modifier on the regular expressions?

**Comment by oplik0** [comment]
Done - rules now have a setting (enabled by default, since I expect it to be the preferred option in most cases tbh) for case insensitivity.
Also, they now support unicode correctly, forgot JS required a flag for that.

**Comment by nfeddema** [comment]
Wonderful, thanks so much!
